spring.application.name=url_shortcut

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortcut
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/dbchangelog.xml
