spring.application.name=url_shortcut

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortcut
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/dbchangelog.xml

jwt.token.secret=bXktdmVyeS1sb25nLXVybC1zaG9ydGN1dC1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcw==
jwt.token.expired=3600000
