CREATE TABLE sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain varchar NOT NULL UNIQUE,
    login varchar NOT NULL UNIQUE,
    password varchar NOT NULL,
    created_at TIMESTAMP NOT NULL
);
