CREATE TABLE shortcut_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url text NOT NULL,
    code varchar NOT NULL UNIQUE,
    total BIGINT NOT NULL DEFAULT 0,
    site_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT shortcut_urls_site_id_fk FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT shortcut_urls_site_original_url_unique UNIQUE (site_id, original_url)
);
